### PR TITLE
add sequence diagram

### LINKED ISSUE #31: Add flow diagrams

### PR DESCRIPTION
**Pull request by aaronpk**
closes #31

This builds on my local machine without changing to v3!

### CODE REVIEW

**Comment by selfissued** [comment]
Please change labels to Title Case.  Specifically, change spellings in both diagrams to:

Resource Request Without Access Token
Resource Request With Access Token
RS Metadata Response
AS Metadata Response
Resource Response
Validate RS Metadata
Build AS Metadata URL
Client Obtains Access Token

**Review by selfissued — APPROVED** [review]

**Comment by selfissued** [comment]
Cc @PieterKas

**Comment by aaronpk** [comment]
Preview links:

HTML: https://drafts.oauth.net/draft-ietf-oauth-resource-metadata/aaronpk-diagram/draft-ietf-oauth-resource-metadata.html#section-5

Text: https://drafts.oauth.net/draft-ietf-oauth-resource-metadata/aaronpk-diagram/draft-ietf-oauth-resource-metadata.txt

**Comment by selfissued** [comment]
Thanks for the preview links.  But they lead me to request two nitpicky changes. ;-)

In the ASCII diagram, move "Client" to the first line of the box.
In the SVG diagram, change "with" to "With".

Thanks.

**Comment by PieterKas** [comment]
Looks good to me, thanks for adding this, it brings a lot of clarity.

**Review by PieterKas — APPROVED** [review]

**Pull request merged**
