### PR TITLE
Add metadata values for DPoP and MTLS

### LINKED ISSUE #48: Declaring support for DPoP and Certificate-Bound Access Tokens
It would be interesting for the resource server to declare support for:

* [DPoP](https://datatracker.ietf.org/doc/html/rfc9449)
* [Certificate-Bound Access Token](https://www.rfc-editor.org/rfc/rfc8705)

The authorization server could use this information to detect that it can issue this type of access tokens for the target Resource Server.

### PR DESCRIPTION
**Pull request by selfissued**
Fixes #48 

Cc: @randomstuff

### CODE REVIEW

**Comment by randomstuff** [comment]
Small comments:

* One confusing thing is that `dpop_bound_access_tokens` declares that RS **always requires** DPoP whereas `tls_client_certificate_bound_access_tokens`** declares whether the Rs supports mTLS-bound access tokens.
* I am wondering if `dpop_bound_access_tokens` makes sense in the context of the RS. It makes a lot of sens =e in the context of the client application bit it might make more sense for the RS to have a parameter which says "I always require sender-constrained access tokens" in order to different different type of clients (?).

**Comment by selfissued** [comment]
As I'm sure you can tell, I reused the existing metadata values from the DPoP and MTLS specs, applying them here.  That seemed like at least the right starting point.  I agree that the two mechanisms aren't parallel (including that there's no way to specify what MTLS algorithms are supported).

If we do anything else, I would prefer to add something like an `access_token_types_supported` field with defined values `[bearer, mtls, dpop]` and delete `dpop_bound_access_tokens`.

What do people think?

**Comment by randomstuff** [comment]
Note: I would expect `access_token_types_supported` to list actually defined `acces_token_types` (from the [registry](https://www.iana.org/assignments/oauth-parameters/oauth-parameters.xhtml#token-types)) and `mtls` is not one of them because it (typically) uses `"token_type":"bearer"`.

**Comment by randomstuff** [comment]
I would suggest simply removing `dpop_bound_access_tokens` because I am not sure it is useful. However, I am not sure if this is right or wrong.

**Comment by selfissued** [comment]
Good point about access token types having a registry and MTLS not being in the registry.  So we shouldn't do what I proposed in the comments.

**Comment by selfissued** [comment]
Having `dpop_bound_access_tokens` to say that DPoP tokens are required is very useful.  It means that the WWW-Authenticate dance saying that the client has to use DPoP shown in Figure 15 at https://www.rfc-editor.org/rfc/rfc9449.html#http-401-response-protected-req-without-auth can be skipped - saving a protocol round trip.

So I'm thinking that we should leave the metadata parameters as they are in the PR.

**Comment by randomstuff** [comment]
> Having dpop_bound_access_tokens to say that DPoP tokens are required is very useful. It means that the WWW-Authenticate dance saying that the client has to use DPoP shown in Figure 15 at https://www.rfc-editor.org/rfc/rfc9449.html#http-401-response-protected-req-without-auth can be skipped - saving a protocol round trip.

This *could* be supported by the `access_token_types_supported` parameter (which could have the `bearer` and `DPoP` values).

**Comment by selfissued** [comment]
@randomstuff, you talked me out of `access_token_types_supported` earlier because it's a mix of things with and outside of an existing registry.  And I believe you were right.

I'm prone to leave things as-is, pending @aaronpk's feedback.

**Comment by aaronpk** [comment]
I agree the mismatch of DPoP *required* vs MTLS *supported* is weird.

>  I reused the existing metadata values from the DPoP and MTLS specs, applying them here

Which DPoP metadata is that? I see one for [client metadata](https://datatracker.ietf.org/doc/html/rfc9449#section-12.10) which indicates whether the client always uses DPoP for token requests. But that isn't the same thing. It is also only about the token *request* to the authorization server, not about requests to the resource server.

**Comment by selfissued** [comment]
One gets the DPoP-supported bit from whether `dpop_signing_alg_values_supported` is present or not.  So you have _supported_ bits for both mechanisms.

The difference between DPoP and MTLS that this PR tries to accurately reflect is that DPoP has a mechanism to say that DPoP is required whereas MTLS doesn't.  The required bit for DPoP is in `dpop_bound_access_tokens`.  I decided not to add such a bit for MTLS, but could if you guys feel that it's needed.

**Comment by aaronpk** [comment]
I see, that's fine. Can we make it more explicit and make it `dpop_bound_access_tokens_required` so that at least we don't have the inconsistency of `tls_client_certificate_bound_access_tokens` meaning "supported" and `dpop_bound_access_tokens` meaning "required"?

**Comment by randomstuff** [comment]
@aaronpk, the inconsistency comes from [RFC9447](https://www.rfc-editor.org/rfc/rfc9449.html#name-client-registration-metadat), which defines `dpop_bound_access_tokens` as:

> A boolean value specifying whether the client always uses DPoP for token requests. If omitted, the default value is false.

I agree that this should probably have been named `dpop_bound_access_token(s)_required` instead but here we are.

Now, it probably makes sense to use the same (arguably bogus) name here for the same semantic.

**Comment by aaronpk** [comment]
I actually think it's not necessary to use the same term, since RFC9447 is talking about it from the opposite point of view. In 9447 it's about whether the *client* always uses DPoP, whereas what we're talking about is whether the *server* requires DPoP. It would be weird in 9447 to use `_required`, since the semantic is not that the client *requires* DPoP, it's about whether the client always includes DPoP proofs in its requests. So the semantic is actually different.

**Comment by selfissued** [comment]
Based on the discussion here, I changed `dpop_bound_access_tokens` to `dpop_bound_access_tokens_required`.

**Review by aaronpk — APPROVED** [review]

**Pull request merged**
